<?php

/**
 * @file
 * Provides a SEPA payment method for Drupal Commerce
 *  
 */


/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_sepa_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['commerce_sepa'] = array(
    'title' => t('SEPA Payment'),
    'description' => t('Demonstrates credit card payment during checkout and serves as a development example.'),
    'active' => TRUE,
  );

  return $payment_methods;
}

/**
 * Payment method callback: submit form.
 */
function commerce_sepa_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  module_load_include('inc', 'commerce_sepa', 'include/commerce_sepa.iban_bic');

  // Default to a known test credit card number. For valid numbers of other card
  // types see: http://www.rimmkaufman.com/blog/credit-card-test-numbers/09112007/
  return commerce_sepa_iban_bic_form(array(), array('number' => '4111111111111111'));
}

/**
 * Payment method callback: submit form validation.
 */
function commerce_sepa_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {
  // Validate the credit card fields.
  module_load_include('inc', 'commerce_sepa', 'include/commerce_sepa.iban_bic');
	
  $settings = array(
    'form_parents' => array_merge($form_parents, array('credit_card')),
  );

  // Even though a form error triggered by the validate handler would be enough
  // to stop the submission of the form, it's not enough to stop it from a
  // Commerce standpoint because of the combined validation / submission going
  // on per-pane in the checkout form. Thus even with a call to form_set_error()
  // this validate handler must still return FALSE.
  if (!commerce_sepa_iban_bic_validate($pane_values['sepa'], $settings)) {
    return FALSE;
  }
}

/**
 * Payment method callback: submit form submission.
 */
function commerce_sepa_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  // Just as an example, we might store information in the order object from the
  // payment parameters, though we would never save a full credit card number,
  // even in examples!

	
	//$number = $pane_values['credit_card']['number'];
  //$pane_values['credit_card']['number'] = substr($number, 0, 4) . str_repeat('-', strlen($number) - 8) . substr($number, -4);
	
  $order->data['commerce_sepa'] = $pane_values;

  // Every attempted transaction should result in a new transaction entity being
  // created for the order to log either the success or the failure.
  commerce_sepa_transaction($payment_method, $order, $charge);
}

/**
 * Creates an example payment transaction for the specified charge amount.
 *
 * @param $payment_method
 *   The payment method instance object used to charge this payment.
 * @param $order
 *   The order object the payment applies to.
 * @param $charge
 *   An array indicating the amount and currency code to charge.
 */
function commerce_sepa_transaction($payment_method, $order, $charge) {
  $sepa_details = $order->data['commerce_sepa']['sepa'];

  $transaction = commerce_payment_transaction_new('commerce_sepa', $order->order_id);
  $transaction->instance_id = $payment_method['instance_id'];
  $transaction->amount = $charge['amount'];
  $transaction->currency_code = $charge['currency_code'];
  $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;

  $transaction->message = 'IBAN: @iban<br/>BIC: @bic';
  $transaction->message_variables = array(
    '@iban' => $sepa_details['iban'],
    '@bic' => $sepa_details['bic'],
  );

  commerce_payment_transaction_save($transaction);
}


function commerce_sepa_default_rules_configuration() {
  $configs = array();
  $rule = '{ "commerce_sepa_sent_sepa_direct_debit_mandate" : {
    "LABEL" : "Sent SEPA Direct Debit Mandate",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "TAGS" : [ "Commerce", "Commerce SEPA" ],
    "REQUIRES" : [ "commerce_payment", "rules_i18n", "rules", "commerce_checkout" ],
    "ON" : { "commerce_checkout_complete" : [] },
    "IF" : [
      { "commerce_payment_selected_payment_method" : { "commerce_order" : [ "commerce_order" ], "method_id" : "commerce_sepa" } }
    ],
    "DO" : [
      { "mail" : {
          "to" : [ "commerce-order:mail" ],
          "subject" : "SEPA Direct Debit Mandate for order [commerce-order:order-number]",
          "message" : "SEPA-Lastschriftmandat\r\n\r\nZahlungsempf\u00e4nger: [commerce-order:commerce_customer_billing]\r\nGl\u00e4ubiger-Identifikationsnummer: DEXXXXXXXXXXX\r\nMandatsreferenz: [commerce-order:order-number]\r\n\r\nIch erm\u00e4chtige den Zahlungsempf\u00e4nger, Zahlungen von meinem Konto mittels Lastschrift einzuziehen. Zugleich weise ich mein Kreditinstitut an, die von dem Zahlungsempf\u00e4nger auf mein Konto gezogenen Lastschriften einzul\u00f6sen.\r\n\r\nHinweis: Ich kann innerhalb von acht Wochen, beginnend mit dem Belastungsdatum, die Erstattung des belasteten Betrages verlangen. Es gelten dabei die mit meinem Kreditinstitut vereinbarten Bedingungen.\r\n\r\n[site:name]",
          "language" : [ "commerce-order:state" ]
        }
      }
    ]
  }
	}';
  $configs['commerce_sepa_sent_sepa_direct_debit_mandate'] = rules_import($rule);
  return $configs;
}
